POST http://localhost:8080/api/score
Content-Type: application/json

{
  "game": "BlockPuzzle",
  "player": "Xabi",
  "points": 300,
  "playedOn": "2021-05-03T00:00:00Z"
}

###
POST http://localhost:8080/api/comment
Content-Type: application/json

{
  "game": "BlockPuzzle",
  "player": "Marshmello",
  "comment": "This game is awesome!",
  "commentedOn": "2023-05-02T00:00:00Z"
}

###
POST http://localhost:8080/api/rating
Content-Type: application/json

{
  "game": "BlockPuzzle",
  "player": "Pedro",
  "rating": 5,
  "ratedOn": "2022-07-02T00:00:00Z"
}

###
GET http://localhost:8080/api/score/BlockPuzzle
Accept: application/json

###
GET http://localhost:8080/api/comment/BlockPuzzle
Accept: application/json

###
GET http://localhost:8080/api/rating/BlockPuzzle
Accept: application/json

###
GET http://localhost:8080/api/rating/BlockPuzzle/IShowSpeed
Accept: application/json